### ISSUE TITLE
TexturesAndFbos: Changes and Notes

### ISSUE THREAD

**Issue by simongeilfus** [simongeilfus/Cinder#2]
https://github.com/simongeilfus/Cinder/tree/TexturesAndFbos
##### gl/Texture
- [x] `gl::TextureBase::Format::setSamples`
- [x] `gl::TextureBase::Format::getSamples`
- [x] `gl::Texture2d::Format::samples`
- [x] `gl::Texture3d::Format::samples`
##### gl/Fbo
- [x] `gl::Fbo::createEmpty` (see https://github.com/cinder/Cinder/issues/1191)
- [ ] `gl::Fbo multisampling support for texture2dArray` (see https://github.com/cinder/Cinder/issues/1191)
- [x] `gl::Fbo::Format::depthTexture` doesn't support `GL_DEPTH_STENCIL` format (see https://github.com/cinder/Cinder/issues/1501)
- [ ] `gl::Fbo better support for textureCubemap` (see https://github.com/cinder/Cinder/issues/1320 and https://forum.libcinder.org/#Topic/23286000002501045)
- [x] `gl::Fbo better support for texture3d and texture2dArray` (see https://github.com/cinder/Cinder/issues/1191)
- [x] `gl::Fbo::attach`
- [ ] `gl::Fbo::attach multisampling support`
- [ ] `gl::Fbo::Format option to switch to texture based multisampling`
- [x] `static gl::Fbo::checkStatus`
- [x] Fix for "gl::Fbo default depth-stencil renderbuffer is created twice on desktop" (see https://github.com/cinder/Cinder/issues/1503)
##### gl/wrapper
- [x] `gl::framebufferRenderbuffer`
- [x] `gl::framebufferTexture`
- [x] `gl::frameBufferTextureLayer`
- [x] `gl::drawBuffers( const std::vector<GLenum> &bufs );`
- [x] `gl::getMaxSamples` 
- [x] `gl::getMaxColorTextureSamples`
- [x] `gl::getMaxDepthTextureSamples`
##### gl/scoped
- [x] `gl::ScopedDrawBuffers` (see https://github.com/cinder/Cinder/issues/736)  
##### gl/Environment
- [x] `gl::Environment::supportsTextureMultisample`
- [x] `gl::Environment::supportsTextureStorageMultisample`  
##### gl/platform
- [x] `CINDER_GL_HAS_TEXTURE_MULTISAMPLE`
- [x] `CINDER_GL_HAS_TEXTURE_2D_STORAGE_MULTISAMPLE`
- [x] `CINDER_GL_HAS_TEXTURE_3D_STORAGE_MULTISAMPLE`
##### tests/_opengl
- [ ] Tests on Linux, MacOS, iOS and GL ES 3 !!!
- [x] EmptyFbo
- [ ] Separate texture multisample tests from EmptyFbo
- [ ] Layered Rendering
### Related pull requests
- Added mipmap support for 2d texture arrays : https://github.com/cinder/Cinder/pull/1432
- Texture*::getFormat() const : https://github.com/cinder/Cinder/pull/1217
### Notes
- Could deprecate gl::Fbo::getMaxSamples() to gl::getMaxSamples() as it's not onle related to Fbos (found only two breaking changes in Fbo.cpp#L81, nothing in samples)
- maximum number of samples of a texture is not GL_MAX_SAMPLES but GL_MAX_COLOR_TEXTURE_SAMPLES and GL_MAX_DEPTH_TEXTURE_SAMPLES ... No idea if those might return different values on other gpus.
- made gl::Fbo::checkStatus() static
- should we have both ScopedDrawBuffers and ScopedDrawBuffer or one class is enough for both glDrawBuffer and glDrawBuffers?
#### Textures Multisample support :

| Function | Target | Desktop | ES | Cinder Proposed Feature Name |
| --- | --- | --- | --- | --- |
| glTexImage2DMultisample | GL_TEXTURE_2D_MULTISAMPLE | GL3.2 |  | CINDER_GL_HAS_TEXTURE_MULTISAMPLE |
| glTexImage3DMultisample | GL_TEXTURE_2D_MULTISAMPLE_ARRAY | GL3.2 |  | CINDER_GL_HAS_TEXTURE_MULTISAMPLE |
| glTexStorage2DMultisample | GL_TEXTURE_2D_MULTISAMPLE | GL4.3 | ES3.1 | CINDER_GL_HAS_TEXTURE_2D_STORAGE_MULTISAMPLE |
| glTexStorage3DMultisample | GL_TEXTURE_2D_MULTISAMPLE_ARRAY | GL4.3 |  | CINDER_GL_HAS_TEXTURE_2D_STORAGE_MULTISAMPLE |

**Comment by thyrrestrup** [comment]
It would be a very welcome update to get at least some of these changes merged into Cinder.
Nice work!

**Comment by totalgee** [comment]
Thanks, it's great Fbo is getting some love.  (-;

Not sure this is useful "generally", but for [my purposes](https://discourse.libcinder.org/t/sli-multicasting-with-multisampled-fbos/1123/2) it would have been useful to have:

- ability to bind the *resolved part* of a multisampled Fbo, using the Cinder Fbo API.  Normally, when you `bindFramebuffer()` (it seems to assume you're binding in order to *draw* to it, even if you pass the `READ` target), it binds the multisampled framebuffer (which is what `getId()` returns if the Fbo has multisampling). Luckily, the method `getResolveId()` existed, so I could do what I needed directly with raw OGL calls (as long as I was careful to restore Cinder's framebuffer binding state after changing it under the covers).

- related to the above: When you call `bindFramebuffer()` with the `GL_READ_FRAMEBUFFER` target, it perhaps shouldn't call `markAsDirty()` ([ref](https://github.com/cinder/Cinder/blob/master/src/cinder/gl/Fbo.cpp#L658)), since you're only going to be using it as a source.

BTW, above, when I say "what I needed," I mean: the ability to blit the *resolved* part of a multisampled Fbo to a different (non-multisampled) Fbo.  In my case, I was doing that using an [OpenGL extension](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_gpu_multicast.txt) blit function (`glMulticastBlitFramebufferNV()`) to transfer it between GPUs.

In my case, I'm not using any extra (color) attachments, so I didn't need to change read/draw buffers for the Fbo blit stuff I was doing (using `glDrawBuffers()` or `glReadBuffer()`).  However, it might be necessary in some cases, if you had multiple attachments.  Is it possible to get/enumerate the attachments (`mAttachments*` entries) once you've created an Fbo?  Doesn't seem to be. (NOTE: This is **not** important for me in this case, mainly just a curiosity...don't worry about it!)

I'm not sure any of this warrants complicating Fbo -- e.g. for different bind cases for READ vs DRAW -- but just thought I'd add my comments here in case they are useful or spark any thoughts. Thanks!
